name: Update Local Inventory Feed

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Kotlin Script
        run: java -jar build/libs/foryoufashion.jar

      - name: Upload XML artifact
        uses: actions/upload-artifact@v2
        with:
          name: updated-local-inventory
          path: updated_local_inventory.xml
